//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 02:53:29 PM MSK 
//


package com.notjuststudio.engine3dgame.colladaConverter.colladaschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}asset"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_animations"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_animation_clips"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_cameras"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_controllers"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_geometries"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_effects"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_force_fields"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_images"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_lights"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_materials"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_nodes"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_physics_materials"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_physics_models"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_physics_scenes"/&gt;
 *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}library_visual_scenes"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="scene" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="instance_physics_scene" type="{http://www.collada.org/2005/11/COLLADASchema}InstanceWithExtra" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="instance_visual_scene" type="{http://www.collada.org/2005/11/COLLADASchema}InstanceWithExtra" minOccurs="0"/&gt;
 *                   &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}extra" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}extra" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.collada.org/2005/11/COLLADASchema}VersionType" /&gt;
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "asset",
    "libraryAnimationsAndLibraryAnimationClipsAndLibraryCameras",
    "scene",
    "extras"
})
@XmlRootElement(name = "COLLADA")
public class COLLADA {

    @XmlElement(required = true)
    protected Asset asset;
    @XmlElements({
        @XmlElement(name = "library_animations", type = LibraryAnimations.class),
        @XmlElement(name = "library_animation_clips", type = LibraryAnimationClips.class),
        @XmlElement(name = "library_cameras", type = LibraryCameras.class),
        @XmlElement(name = "library_controllers", type = LibraryControllers.class),
        @XmlElement(name = "library_geometries", type = LibraryGeometries.class),
        @XmlElement(name = "library_effects", type = LibraryEffects.class),
        @XmlElement(name = "library_force_fields", type = LibraryForceFields.class),
        @XmlElement(name = "library_images", type = LibraryImages.class),
        @XmlElement(name = "library_lights", type = LibraryLights.class),
        @XmlElement(name = "library_materials", type = LibraryMaterials.class),
        @XmlElement(name = "library_nodes", type = LibraryNodes.class),
        @XmlElement(name = "library_physics_materials", type = LibraryPhysicsMaterials.class),
        @XmlElement(name = "library_physics_models", type = LibraryPhysicsModels.class),
        @XmlElement(name = "library_physics_scenes", type = LibraryPhysicsScenes.class),
        @XmlElement(name = "library_visual_scenes", type = LibraryVisualScenes.class)
    })
    protected List<Object> libraryAnimationsAndLibraryAnimationClipsAndLibraryCameras;
    protected Scene scene;
    @XmlElement(name = "extra")
    protected List<Extra> extras;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;

    /**
     * 
     * 						The COLLADA element must contain an asset element.
     * 						
     * 
     * @return
     *     possible object is
     *     {@link Asset }
     *     
     */
    public Asset getAsset() {
        return asset;
    }

    /**
     * Sets the value of the asset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset }
     *     
     */
    public void setAsset(Asset value) {
        this.asset = value;
    }

    /**
     * 
     * 							The COLLADA element may contain any number of library_animations elements.
     * 							Gets the value of the libraryAnimationsAndLibraryAnimationClipsAndLibraryCameras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the libraryAnimationsAndLibraryAnimationClipsAndLibraryCameras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLibraryAnimationsAndLibraryAnimationClipsAndLibraryCameras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LibraryAnimations }
     * {@link LibraryAnimationClips }
     * {@link LibraryCameras }
     * {@link LibraryControllers }
     * {@link LibraryGeometries }
     * {@link LibraryEffects }
     * {@link LibraryForceFields }
     * {@link LibraryImages }
     * {@link LibraryLights }
     * {@link LibraryMaterials }
     * {@link LibraryNodes }
     * {@link LibraryPhysicsMaterials }
     * {@link LibraryPhysicsModels }
     * {@link LibraryPhysicsScenes }
     * {@link LibraryVisualScenes }
     * 
     * 
     */
    public List<Object> getLibraryAnimationsAndLibraryAnimationClipsAndLibraryCameras() {
        if (libraryAnimationsAndLibraryAnimationClipsAndLibraryCameras == null) {
            libraryAnimationsAndLibraryAnimationClipsAndLibraryCameras = new ArrayList<Object>();
        }
        return this.libraryAnimationsAndLibraryAnimationClipsAndLibraryCameras;
    }

    /**
     * Gets the value of the scene property.
     * 
     * @return
     *     possible object is
     *     {@link Scene }
     *     
     */
    public Scene getScene() {
        return scene;
    }

    /**
     * Sets the value of the scene property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scene }
     *     
     */
    public void setScene(Scene value) {
        this.scene = value;
    }

    /**
     * 
     * 						The extra element may appear any number of times.
     * 						Gets the value of the extras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extra }
     * 
     * 
     */
    public List<Extra> getExtras() {
        if (extras == null) {
            extras = new ArrayList<Extra>();
        }
        return this.extras;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * 
     * 					The xml:base attribute allows you to define the base URI for this COLLADA document. See
     * 					http://www.w3.org/TR/xmlbase/ for more information.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="instance_physics_scene" type="{http://www.collada.org/2005/11/COLLADASchema}InstanceWithExtra" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="instance_visual_scene" type="{http://www.collada.org/2005/11/COLLADASchema}InstanceWithExtra" minOccurs="0"/&gt;
     *         &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}extra" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instancePhysicsScenes",
        "instanceVisualScene",
        "extras"
    })
    public static class Scene {

        @XmlElement(name = "instance_physics_scene")
        protected List<InstanceWithExtra> instancePhysicsScenes;
        @XmlElement(name = "instance_visual_scene")
        protected InstanceWithExtra instanceVisualScene;
        @XmlElement(name = "extra")
        protected List<Extra> extras;

        /**
         * Gets the value of the instancePhysicsScenes property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the instancePhysicsScenes property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInstancePhysicsScenes().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InstanceWithExtra }
         * 
         * 
         */
        public List<InstanceWithExtra> getInstancePhysicsScenes() {
            if (instancePhysicsScenes == null) {
                instancePhysicsScenes = new ArrayList<InstanceWithExtra>();
            }
            return this.instancePhysicsScenes;
        }

        /**
         * Gets the value of the instanceVisualScene property.
         * 
         * @return
         *     possible object is
         *     {@link InstanceWithExtra }
         *     
         */
        public InstanceWithExtra getInstanceVisualScene() {
            return instanceVisualScene;
        }

        /**
         * Sets the value of the instanceVisualScene property.
         * 
         * @param value
         *     allowed object is
         *     {@link InstanceWithExtra }
         *     
         */
        public void setInstanceVisualScene(InstanceWithExtra value) {
            this.instanceVisualScene = value;
        }

        /**
         * 
         * 									The extra element may appear any number of times.
         * 									Gets the value of the extras property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extras property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtras().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Extra }
         * 
         * 
         */
        public List<Extra> getExtras() {
            if (extras == null) {
                extras = new ArrayList<Extra>();
            }
            return this.extras;
        }

    }

}
