//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 02:53:29 PM MSK 
//


package com.notjuststudio.engine3dgame.colladaConverter.colladaschema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gl_blend_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="gl_blend_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ZERO"/&gt;
 *     &lt;enumeration value="ONE"/&gt;
 *     &lt;enumeration value="SRC_COLOR"/&gt;
 *     &lt;enumeration value="ONE_MINUS_SRC_COLOR"/&gt;
 *     &lt;enumeration value="DEST_COLOR"/&gt;
 *     &lt;enumeration value="ONE_MINUS_DEST_COLOR"/&gt;
 *     &lt;enumeration value="SRC_ALPHA"/&gt;
 *     &lt;enumeration value="ONE_MINUS_SRC_ALPHA"/&gt;
 *     &lt;enumeration value="DST_ALPHA"/&gt;
 *     &lt;enumeration value="ONE_MINUS_DST_ALPHA"/&gt;
 *     &lt;enumeration value="CONSTANT_COLOR"/&gt;
 *     &lt;enumeration value="ONE_MINUS_CONSTANT_COLOR"/&gt;
 *     &lt;enumeration value="CONSTANT_ALPHA"/&gt;
 *     &lt;enumeration value="ONE_MINUS_CONSTANT_ALPHA"/&gt;
 *     &lt;enumeration value="SRC_ALPHA_SATURATE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "gl_blend_type")
@XmlEnum
public enum GlBlendType {

    ZERO,
    ONE,
    SRC_COLOR,
    ONE_MINUS_SRC_COLOR,
    DEST_COLOR,
    ONE_MINUS_DEST_COLOR,
    SRC_ALPHA,
    ONE_MINUS_SRC_ALPHA,
    DST_ALPHA,
    ONE_MINUS_DST_ALPHA,
    CONSTANT_COLOR,
    ONE_MINUS_CONSTANT_COLOR,
    CONSTANT_ALPHA,
    ONE_MINUS_CONSTANT_ALPHA,
    SRC_ALPHA_SATURATE;

    public String value() {
        return name();
    }

    public static GlBlendType fromValue(String v) {
        return valueOf(v);
    }

}
