//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 02:53:29 PM MSK 
//


package com.notjuststudio.engine3dgame.colladaConverter.colladaschema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gles_texenv_mode_enums.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="gles_texenv_mode_enums"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="REPLACE"/&gt;
 *     &lt;enumeration value="MODULATE"/&gt;
 *     &lt;enumeration value="DECAL"/&gt;
 *     &lt;enumeration value="BLEND"/&gt;
 *     &lt;enumeration value="ADD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "gles_texenv_mode_enums")
@XmlEnum
public enum GlesTexenvModeEnums {

    REPLACE,
    MODULATE,
    DECAL,
    BLEND,
    ADD;

    public String value() {
        return name();
    }

    public static GlesTexenvModeEnums fromValue(String v) {
        return valueOf(v);
    }

}
