//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 02:53:29 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.collada.org/2005/11/COLLADASchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.notjuststudio.engine3dgame.colladaConverter.colladaschema;
