//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.07 at 02:38:33 PM MSK 
//


package com.notjuststudio.engine3dgame.colladaConverter;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.notjuststudio.engine3dgame.colladaConverter package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.notjuststudio.engine3dgame.colladaConverter
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link COLLADA }
     * 
     */
    public COLLADA createCOLLADA() {
        return new COLLADA();
    }

    /**
     * Create an instance of {@link COLLADA.Scene }
     * 
     */
    public COLLADA.Scene createCOLLADAScene() {
        return new COLLADA.Scene();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryVisualScenes }
     * 
     */
    public COLLADA.LibraryVisualScenes createCOLLADALibraryVisualScenes() {
        return new COLLADA.LibraryVisualScenes();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryVisualScenes.VisualScene }
     * 
     */
    public COLLADA.LibraryVisualScenes.VisualScene createCOLLADALibraryVisualScenesVisualScene() {
        return new COLLADA.LibraryVisualScenes.VisualScene();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryVisualScenes.VisualScene.Node }
     * 
     */
    public COLLADA.LibraryVisualScenes.VisualScene.Node createCOLLADALibraryVisualScenesVisualSceneNode() {
        return new COLLADA.LibraryVisualScenes.VisualScene.Node();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry }
     * 
     */
    public COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry createCOLLADALibraryVisualScenesVisualSceneNodeInstanceGeometry() {
        return new COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry.BindMaterial }
     * 
     */
    public COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry.BindMaterial createCOLLADALibraryVisualScenesVisualSceneNodeInstanceGeometryBindMaterial() {
        return new COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry.BindMaterial();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry.BindMaterial.TechniqueCommon }
     * 
     */
    public COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry.BindMaterial.TechniqueCommon createCOLLADALibraryVisualScenesVisualSceneNodeInstanceGeometryBindMaterialTechniqueCommon() {
        return new COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry.BindMaterial.TechniqueCommon();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries }
     * 
     */
    public COLLADA.LibraryGeometries createCOLLADALibraryGeometries() {
        return new COLLADA.LibraryGeometries();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry createCOLLADALibraryGeometriesGeometry() {
        return new COLLADA.LibraryGeometries.Geometry();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry.Mesh }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry.Mesh createCOLLADALibraryGeometriesGeometryMesh() {
        return new COLLADA.LibraryGeometries.Geometry.Mesh();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry.Mesh.Polylist }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry.Mesh.Polylist createCOLLADALibraryGeometriesGeometryMeshPolylist() {
        return new COLLADA.LibraryGeometries.Geometry.Mesh.Polylist();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry.Mesh.Vertices }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry.Mesh.Vertices createCOLLADALibraryGeometriesGeometryMeshVertices() {
        return new COLLADA.LibraryGeometries.Geometry.Mesh.Vertices();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry.Mesh.Source }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry.Mesh.Source createCOLLADALibraryGeometriesGeometryMeshSource() {
        return new COLLADA.LibraryGeometries.Geometry.Mesh.Source();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry.Mesh.Source.TechniqueCommon }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry.Mesh.Source.TechniqueCommon createCOLLADALibraryGeometriesGeometryMeshSourceTechniqueCommon() {
        return new COLLADA.LibraryGeometries.Geometry.Mesh.Source.TechniqueCommon();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry.Mesh.Source.TechniqueCommon.Accessor }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry.Mesh.Source.TechniqueCommon.Accessor createCOLLADALibraryGeometriesGeometryMeshSourceTechniqueCommonAccessor() {
        return new COLLADA.LibraryGeometries.Geometry.Mesh.Source.TechniqueCommon.Accessor();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryMaterials }
     * 
     */
    public COLLADA.LibraryMaterials createCOLLADALibraryMaterials() {
        return new COLLADA.LibraryMaterials();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryMaterials.Material }
     * 
     */
    public COLLADA.LibraryMaterials.Material createCOLLADALibraryMaterialsMaterial() {
        return new COLLADA.LibraryMaterials.Material();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects }
     * 
     */
    public COLLADA.LibraryEffects createCOLLADALibraryEffects() {
        return new COLLADA.LibraryEffects();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect }
     * 
     */
    public COLLADA.LibraryEffects.Effect createCOLLADALibraryEffectsEffect() {
        return new COLLADA.LibraryEffects.Effect();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON createCOLLADALibraryEffectsEffectProfileCOMMON() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique createCOLLADALibraryEffectsEffectProfileCOMMONTechnique() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhong() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.IndexOfRefraction }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.IndexOfRefraction createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongIndexOfRefraction() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.IndexOfRefraction();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Shininess }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Shininess createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongShininess() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Shininess();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Specular }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Specular createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongSpecular() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Specular();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Diffuse }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Diffuse createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongDiffuse() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Diffuse();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Ambient }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Ambient createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongAmbient() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Ambient();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Emission }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Emission createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongEmission() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Emission();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights }
     * 
     */
    public COLLADA.LibraryLights createCOLLADALibraryLights() {
        return new COLLADA.LibraryLights();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light }
     * 
     */
    public COLLADA.LibraryLights.Light createCOLLADALibraryLightsLight() {
        return new COLLADA.LibraryLights.Light();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.Extra }
     * 
     */
    public COLLADA.LibraryLights.Light.Extra createCOLLADALibraryLightsLightExtra() {
        return new COLLADA.LibraryLights.Light.Extra();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.Extra.Technique }
     * 
     */
    public COLLADA.LibraryLights.Light.Extra.Technique createCOLLADALibraryLightsLightExtraTechnique() {
        return new COLLADA.LibraryLights.Light.Extra.Technique();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.TechniqueCommon }
     * 
     */
    public COLLADA.LibraryLights.Light.TechniqueCommon createCOLLADALibraryLightsLightTechniqueCommon() {
        return new COLLADA.LibraryLights.Light.TechniqueCommon();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.TechniqueCommon.Point }
     * 
     */
    public COLLADA.LibraryLights.Light.TechniqueCommon.Point createCOLLADALibraryLightsLightTechniqueCommonPoint() {
        return new COLLADA.LibraryLights.Light.TechniqueCommon.Point();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryCameras }
     * 
     */
    public COLLADA.LibraryCameras createCOLLADALibraryCameras() {
        return new COLLADA.LibraryCameras();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryCameras.Camera }
     * 
     */
    public COLLADA.LibraryCameras.Camera createCOLLADALibraryCamerasCamera() {
        return new COLLADA.LibraryCameras.Camera();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryCameras.Camera.Extra }
     * 
     */
    public COLLADA.LibraryCameras.Camera.Extra createCOLLADALibraryCamerasCameraExtra() {
        return new COLLADA.LibraryCameras.Camera.Extra();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryCameras.Camera.Optics }
     * 
     */
    public COLLADA.LibraryCameras.Camera.Optics createCOLLADALibraryCamerasCameraOptics() {
        return new COLLADA.LibraryCameras.Camera.Optics();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon }
     * 
     */
    public COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon createCOLLADALibraryCamerasCameraOpticsTechniqueCommon() {
        return new COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective }
     * 
     */
    public COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective createCOLLADALibraryCamerasCameraOpticsTechniqueCommonPerspective() {
        return new COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective();
    }

    /**
     * Create an instance of {@link COLLADA.Asset }
     * 
     */
    public COLLADA.Asset createCOLLADAAsset() {
        return new COLLADA.Asset();
    }

    /**
     * Create an instance of {@link COLLADA.Scene.InstanceVisualScene }
     * 
     */
    public COLLADA.Scene.InstanceVisualScene createCOLLADASceneInstanceVisualScene() {
        return new COLLADA.Scene.InstanceVisualScene();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryVisualScenes.VisualScene.Node.Matrix }
     * 
     */
    public COLLADA.LibraryVisualScenes.VisualScene.Node.Matrix createCOLLADALibraryVisualScenesVisualSceneNodeMatrix() {
        return new COLLADA.LibraryVisualScenes.VisualScene.Node.Matrix();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceCamera }
     * 
     */
    public COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceCamera createCOLLADALibraryVisualScenesVisualSceneNodeInstanceCamera() {
        return new COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceCamera();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceLight }
     * 
     */
    public COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceLight createCOLLADALibraryVisualScenesVisualSceneNodeInstanceLight() {
        return new COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceLight();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry.BindMaterial.TechniqueCommon.InstanceMaterial }
     * 
     */
    public COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry.BindMaterial.TechniqueCommon.InstanceMaterial createCOLLADALibraryVisualScenesVisualSceneNodeInstanceGeometryBindMaterialTechniqueCommonInstanceMaterial() {
        return new COLLADA.LibraryVisualScenes.VisualScene.Node.InstanceGeometry.BindMaterial.TechniqueCommon.InstanceMaterial();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry.Mesh.Polylist.Input }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry.Mesh.Polylist.Input createCOLLADALibraryGeometriesGeometryMeshPolylistInput() {
        return new COLLADA.LibraryGeometries.Geometry.Mesh.Polylist.Input();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry.Mesh.Vertices.Input }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry.Mesh.Vertices.Input createCOLLADALibraryGeometriesGeometryMeshVerticesInput() {
        return new COLLADA.LibraryGeometries.Geometry.Mesh.Vertices.Input();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry.Mesh.Source.FloatArray }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry.Mesh.Source.FloatArray createCOLLADALibraryGeometriesGeometryMeshSourceFloatArray() {
        return new COLLADA.LibraryGeometries.Geometry.Mesh.Source.FloatArray();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryGeometries.Geometry.Mesh.Source.TechniqueCommon.Accessor.Param }
     * 
     */
    public COLLADA.LibraryGeometries.Geometry.Mesh.Source.TechniqueCommon.Accessor.Param createCOLLADALibraryGeometriesGeometryMeshSourceTechniqueCommonAccessorParam() {
        return new COLLADA.LibraryGeometries.Geometry.Mesh.Source.TechniqueCommon.Accessor.Param();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryMaterials.Material.InstanceEffect }
     * 
     */
    public COLLADA.LibraryMaterials.Material.InstanceEffect createCOLLADALibraryMaterialsMaterialInstanceEffect() {
        return new COLLADA.LibraryMaterials.Material.InstanceEffect();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.IndexOfRefraction.Float }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.IndexOfRefraction.Float createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongIndexOfRefractionFloat() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.IndexOfRefraction.Float();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Shininess.Float }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Shininess.Float createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongShininessFloat() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Shininess.Float();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Specular.Color }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Specular.Color createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongSpecularColor() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Specular.Color();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Diffuse.Color }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Diffuse.Color createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongDiffuseColor() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Diffuse.Color();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Ambient.Color }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Ambient.Color createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongAmbientColor() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Ambient.Color();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Emission.Color }
     * 
     */
    public COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Emission.Color createCOLLADALibraryEffectsEffectProfileCOMMONTechniquePhongEmissionColor() {
        return new COLLADA.LibraryEffects.Effect.ProfileCOMMON.Technique.Phong.Emission.Color();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.Extra.Technique.Dist }
     * 
     */
    public COLLADA.LibraryLights.Light.Extra.Technique.Dist createCOLLADALibraryLightsLightExtraTechniqueDist() {
        return new COLLADA.LibraryLights.Light.Extra.Technique.Dist();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.Extra.Technique.Energy }
     * 
     */
    public COLLADA.LibraryLights.Light.Extra.Technique.Energy createCOLLADALibraryLightsLightExtraTechniqueEnergy() {
        return new COLLADA.LibraryLights.Light.Extra.Technique.Energy();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.Extra.Technique.Gamma }
     * 
     */
    public COLLADA.LibraryLights.Light.Extra.Technique.Gamma createCOLLADALibraryLightsLightExtraTechniqueGamma() {
        return new COLLADA.LibraryLights.Light.Extra.Technique.Gamma();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.Extra.Technique.HaloIntensity }
     * 
     */
    public COLLADA.LibraryLights.Light.Extra.Technique.HaloIntensity createCOLLADALibraryLightsLightExtraTechniqueHaloIntensity() {
        return new COLLADA.LibraryLights.Light.Extra.Technique.HaloIntensity();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.Extra.Technique.ShadowB }
     * 
     */
    public COLLADA.LibraryLights.Light.Extra.Technique.ShadowB createCOLLADALibraryLightsLightExtraTechniqueShadowB() {
        return new COLLADA.LibraryLights.Light.Extra.Technique.ShadowB();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.Extra.Technique.ShadowG }
     * 
     */
    public COLLADA.LibraryLights.Light.Extra.Technique.ShadowG createCOLLADALibraryLightsLightExtraTechniqueShadowG() {
        return new COLLADA.LibraryLights.Light.Extra.Technique.ShadowG();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.Extra.Technique.ShadowR }
     * 
     */
    public COLLADA.LibraryLights.Light.Extra.Technique.ShadowR createCOLLADALibraryLightsLightExtraTechniqueShadowR() {
        return new COLLADA.LibraryLights.Light.Extra.Technique.ShadowR();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryLights.Light.TechniqueCommon.Point.Color }
     * 
     */
    public COLLADA.LibraryLights.Light.TechniqueCommon.Point.Color createCOLLADALibraryLightsLightTechniqueCommonPointColor() {
        return new COLLADA.LibraryLights.Light.TechniqueCommon.Point.Color();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryCameras.Camera.Extra.Technique }
     * 
     */
    public COLLADA.LibraryCameras.Camera.Extra.Technique createCOLLADALibraryCamerasCameraExtraTechnique() {
        return new COLLADA.LibraryCameras.Camera.Extra.Technique();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective.Xfov }
     * 
     */
    public COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective.Xfov createCOLLADALibraryCamerasCameraOpticsTechniqueCommonPerspectiveXfov() {
        return new COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective.Xfov();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective.Znear }
     * 
     */
    public COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective.Znear createCOLLADALibraryCamerasCameraOpticsTechniqueCommonPerspectiveZnear() {
        return new COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective.Znear();
    }

    /**
     * Create an instance of {@link COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective.Zfar }
     * 
     */
    public COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective.Zfar createCOLLADALibraryCamerasCameraOpticsTechniqueCommonPerspectiveZfar() {
        return new COLLADA.LibraryCameras.Camera.Optics.TechniqueCommon.Perspective.Zfar();
    }

    /**
     * Create an instance of {@link COLLADA.Asset.Contributor }
     * 
     */
    public COLLADA.Asset.Contributor createCOLLADAAssetContributor() {
        return new COLLADA.Asset.Contributor();
    }

    /**
     * Create an instance of {@link COLLADA.Asset.Unit }
     * 
     */
    public COLLADA.Asset.Unit createCOLLADAAssetUnit() {
        return new COLLADA.Asset.Unit();
    }

}
